runtime: python27
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

- url: /static/(.*\.svg)
  static_files: static/\1
  upload: static/(.*\.svg)
  http_headers:
    Content-Type: images/svg+xml

- url: /tasks/.*
  script: main.app
  login: admin

- url: /.*
  script: main.app

libraries:
- name: lxml    
  version: latest

- name: ssl
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^venv$

builtins:
- deferred: on